# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: temporal/api/errordetails/v1/message.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class NotFoundFailure(betterproto.Message):
    current_cluster: str = betterproto.string_field(1)
    active_cluster: str = betterproto.string_field(2)


@dataclass
class WorkflowExecutionAlreadyStartedFailure(betterproto.Message):
    start_request_id: str = betterproto.string_field(1)
    run_id: str = betterproto.string_field(2)


@dataclass
class NamespaceNotActiveFailure(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    current_cluster: str = betterproto.string_field(2)
    active_cluster: str = betterproto.string_field(3)


@dataclass
class ClientVersionNotSupportedFailure(betterproto.Message):
    client_version: str = betterproto.string_field(1)
    client_name: str = betterproto.string_field(2)
    supported_versions: str = betterproto.string_field(3)


@dataclass
class ServerVersionNotSupportedFailure(betterproto.Message):
    server_version: str = betterproto.string_field(1)
    client_supported_server_versions: str = betterproto.string_field(2)


@dataclass
class NamespaceAlreadyExistsFailure(betterproto.Message):
    pass


@dataclass
class CancellationAlreadyRequestedFailure(betterproto.Message):
    pass


@dataclass
class QueryFailedFailure(betterproto.Message):
    pass


@dataclass
class PermissionDeniedFailure(betterproto.Message):
    reason: str = betterproto.string_field(1)
